import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "The Blog – This is a blog built with Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>Header</h1>
        </header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
